package core

func MakeConfig() map[string]any {
	return map[string]any{
		"main": map[string]any{
			"name": "YuGiOh",
		},
		"feature": map[string]any{
			"test": map[string]any{
				"options": map[string]any{
					"active": false,
				},
			},
		},
		"options": map[string]any{
			"base": "https://db.ygoprodeck.com/api/v7",
			"auth": map[string]any{
				"prefix": "Bearer",
			},
			"headers": map[string]any{
				"content-type": "application/json",
			},
			"entity": map[string]any{
				"cardinfo": map[string]any{},
			},
		},
		"entity": map[string]any{
			"cardinfo": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "archetype",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "atk",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "attribute",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 2,
					},
					map[string]any{
						"name": "banlist_info",
						"req": false,
						"type": "`$OBJECT`",
						"active": true,
						"index$": 3,
					},
					map[string]any{
						"name": "beta_name",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 4,
					},
					map[string]any{
						"name": "card_image",
						"req": false,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 5,
					},
					map[string]any{
						"name": "card_price",
						"req": false,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 6,
					},
					map[string]any{
						"name": "card_set",
						"req": false,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 7,
					},
					map[string]any{
						"name": "def",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 8,
					},
					map[string]any{
						"name": "desc",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 9,
					},
					map[string]any{
						"name": "downvote",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 10,
					},
					map[string]any{
						"name": "format",
						"req": false,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 11,
					},
					map[string]any{
						"name": "frame_type",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 12,
					},
					map[string]any{
						"name": "genesys_point",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 13,
					},
					map[string]any{
						"name": "has_effect",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 14,
					},
					map[string]any{
						"name": "id",
						"req": true,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 15,
					},
					map[string]any{
						"name": "konami_id",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 16,
					},
					map[string]any{
						"name": "level",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 17,
					},
					map[string]any{
						"name": "linkmarker",
						"req": false,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 18,
					},
					map[string]any{
						"name": "linkval",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 19,
					},
					map[string]any{
						"name": "md_rarity",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 20,
					},
					map[string]any{
						"name": "name",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 21,
					},
					map[string]any{
						"name": "ocg_date",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 22,
					},
					map[string]any{
						"name": "race",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 23,
					},
					map[string]any{
						"name": "scale",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 24,
					},
					map[string]any{
						"name": "tcg_date",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 25,
					},
					map[string]any{
						"name": "treated_a",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 26,
					},
					map[string]any{
						"name": "type",
						"req": true,
						"type": "`$STRING`",
						"active": true,
						"index$": 27,
					},
					map[string]any{
						"name": "upvote",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 28,
					},
					map[string]any{
						"name": "view",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 29,
					},
					map[string]any{
						"name": "viewsweek",
						"req": false,
						"type": "`$INTEGER`",
						"active": true,
						"index$": 30,
					},
					map[string]any{
						"name": "ygoprodeck_url",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 31,
					},
				},
				"name": "cardinfo",
				"op": map[string]any{
					"list": map[string]any{
						"name": "list",
						"points": []any{
							map[string]any{
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"example": "Blue-Eyes",
											"kind": "query",
											"name": "archetype",
											"orig": "archetype",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "2100",
											"kind": "query",
											"name": "atk",
											"orig": "atk",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "WIND",
											"kind": "query",
											"name": "attribute",
											"orig": "attribute",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "tcg",
											"kind": "query",
											"name": "banlist",
											"orig": "banlist",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "Metal Raiders",
											"kind": "query",
											"name": "cardset",
											"orig": "cardset",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "tcg",
											"kind": "query",
											"name": "dateregion",
											"orig": "dateregion",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "2000",
											"kind": "query",
											"name": "def",
											"orig": "def",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "2002-08-23",
											"kind": "query",
											"name": "enddate",
											"orig": "enddate",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "Wizard",
											"kind": "query",
											"name": "fname",
											"orig": "fname",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "Speed Duel",
											"kind": "query",
											"name": "format",
											"orig": "format",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "has_effect",
											"orig": "has_effect",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": "6983839",
											"kind": "query",
											"name": "id",
											"orig": "id",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "konami_id",
											"orig": "konami_id",
											"reqd": false,
											"type": "`$INTEGER`",
											"active": true,
										},
										map[string]any{
											"example": "4",
											"kind": "query",
											"name": "level",
											"orig": "level",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "link",
											"orig": "link",
											"reqd": false,
											"type": "`$INTEGER`",
											"active": true,
										},
										map[string]any{
											"example": "top,bottom",
											"kind": "query",
											"name": "linkmarker",
											"orig": "linkmarker",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "misc",
											"orig": "misc",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "Dark Magician",
											"kind": "query",
											"name": "name",
											"orig": "name",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "Wyrm",
											"kind": "query",
											"name": "race",
											"orig": "race",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "scale",
											"orig": "scale",
											"reqd": false,
											"type": "`$INTEGER`",
											"active": true,
										},
										map[string]any{
											"example": "name",
											"kind": "query",
											"name": "sort",
											"orig": "sort",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "staple",
											"orig": "staple",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "2000-01-01",
											"kind": "query",
											"name": "startdate",
											"orig": "startdate",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "tcgplayer_data",
											"orig": "tcgplayer_data",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "Spell Card",
											"kind": "query",
											"name": "type",
											"orig": "type",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/cardinfo.php",
								"parts": []any{
									"cardinfo.php",
								},
								"select": map[string]any{
									"exist": []any{
										"archetype",
										"atk",
										"attribute",
										"banlist",
										"cardset",
										"dateregion",
										"def",
										"enddate",
										"fname",
										"format",
										"has_effect",
										"id",
										"konami_id",
										"level",
										"link",
										"linkmarker",
										"misc",
										"name",
										"race",
										"scale",
										"sort",
										"staple",
										"startdate",
										"tcgplayer_data",
										"type",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "list",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
		},
	}
}

func makeFeature(name string) Feature {
	switch name {
	case "test":
		if NewTestFeatureFunc != nil {
			return NewTestFeatureFunc()
		}
	default:
		if NewBaseFeatureFunc != nil {
			return NewBaseFeatureFunc()
		}
	}
	return nil
}
