# YuGiOh SDK configuration

module YuGiOhConfig
  def self.make_config
    {
      "main" => {
        "name" => "YuGiOh",
      },
      "feature" => {
        "test" => {
          "options" => {
            "active" => false,
          },
        },
      },
      "options" => {
        "base" => "https://db.ygoprodeck.com/api/v7",
        "auth" => {
          "prefix" => "Bearer",
        },
        "headers" => {
          "content-type" => "application/json",
        },
        "entity" => {
          "cardinfo" => {},
        },
      },
      "entity" => {
        "cardinfo" => {
          "fields" => [
            {
              "name" => "archetype",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 0,
            },
            {
              "name" => "atk",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 1,
            },
            {
              "name" => "attribute",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 2,
            },
            {
              "name" => "banlist_info",
              "req" => false,
              "type" => "`$OBJECT`",
              "active" => true,
              "index$" => 3,
            },
            {
              "name" => "beta_name",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 4,
            },
            {
              "name" => "card_image",
              "req" => false,
              "type" => "`$ARRAY`",
              "active" => true,
              "index$" => 5,
            },
            {
              "name" => "card_price",
              "req" => false,
              "type" => "`$ARRAY`",
              "active" => true,
              "index$" => 6,
            },
            {
              "name" => "card_set",
              "req" => false,
              "type" => "`$ARRAY`",
              "active" => true,
              "index$" => 7,
            },
            {
              "name" => "def",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 8,
            },
            {
              "name" => "desc",
              "req" => true,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 9,
            },
            {
              "name" => "downvote",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 10,
            },
            {
              "name" => "format",
              "req" => false,
              "type" => "`$ARRAY`",
              "active" => true,
              "index$" => 11,
            },
            {
              "name" => "frame_type",
              "req" => true,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 12,
            },
            {
              "name" => "genesys_point",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 13,
            },
            {
              "name" => "has_effect",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 14,
            },
            {
              "name" => "id",
              "req" => true,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 15,
            },
            {
              "name" => "konami_id",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 16,
            },
            {
              "name" => "level",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 17,
            },
            {
              "name" => "linkmarker",
              "req" => false,
              "type" => "`$ARRAY`",
              "active" => true,
              "index$" => 18,
            },
            {
              "name" => "linkval",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 19,
            },
            {
              "name" => "md_rarity",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 20,
            },
            {
              "name" => "name",
              "req" => true,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 21,
            },
            {
              "name" => "ocg_date",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 22,
            },
            {
              "name" => "race",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 23,
            },
            {
              "name" => "scale",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 24,
            },
            {
              "name" => "tcg_date",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 25,
            },
            {
              "name" => "treated_a",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 26,
            },
            {
              "name" => "type",
              "req" => true,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 27,
            },
            {
              "name" => "upvote",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 28,
            },
            {
              "name" => "view",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 29,
            },
            {
              "name" => "viewsweek",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 30,
            },
            {
              "name" => "ygoprodeck_url",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 31,
            },
          ],
          "name" => "cardinfo",
          "op" => {
            "list" => {
              "name" => "list",
              "points" => [
                {
                  "args" => {
                    "query" => [
                      {
                        "example" => "Blue-Eyes",
                        "kind" => "query",
                        "name" => "archetype",
                        "orig" => "archetype",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "2100",
                        "kind" => "query",
                        "name" => "atk",
                        "orig" => "atk",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "WIND",
                        "kind" => "query",
                        "name" => "attribute",
                        "orig" => "attribute",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "tcg",
                        "kind" => "query",
                        "name" => "banlist",
                        "orig" => "banlist",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "Metal Raiders",
                        "kind" => "query",
                        "name" => "cardset",
                        "orig" => "cardset",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "tcg",
                        "kind" => "query",
                        "name" => "dateregion",
                        "orig" => "dateregion",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "2000",
                        "kind" => "query",
                        "name" => "def",
                        "orig" => "def",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "2002-08-23",
                        "kind" => "query",
                        "name" => "enddate",
                        "orig" => "enddate",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "Wizard",
                        "kind" => "query",
                        "name" => "fname",
                        "orig" => "fname",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "Speed Duel",
                        "kind" => "query",
                        "name" => "format",
                        "orig" => "format",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "has_effect",
                        "orig" => "has_effect",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "example" => "6983839",
                        "kind" => "query",
                        "name" => "id",
                        "orig" => "id",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "konami_id",
                        "orig" => "konami_id",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "example" => "4",
                        "kind" => "query",
                        "name" => "level",
                        "orig" => "level",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "link",
                        "orig" => "link",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "example" => "top,bottom",
                        "kind" => "query",
                        "name" => "linkmarker",
                        "orig" => "linkmarker",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "misc",
                        "orig" => "misc",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "Dark Magician",
                        "kind" => "query",
                        "name" => "name",
                        "orig" => "name",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "Wyrm",
                        "kind" => "query",
                        "name" => "race",
                        "orig" => "race",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "scale",
                        "orig" => "scale",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "example" => "name",
                        "kind" => "query",
                        "name" => "sort",
                        "orig" => "sort",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "staple",
                        "orig" => "staple",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "2000-01-01",
                        "kind" => "query",
                        "name" => "startdate",
                        "orig" => "startdate",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "tcgplayer_data",
                        "orig" => "tcgplayer_data",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "Spell Card",
                        "kind" => "query",
                        "name" => "type",
                        "orig" => "type",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/cardinfo.php",
                  "parts" => [
                    "cardinfo.php",
                  ],
                  "select" => {
                    "exist" => [
                      "archetype",
                      "atk",
                      "attribute",
                      "banlist",
                      "cardset",
                      "dateregion",
                      "def",
                      "enddate",
                      "fname",
                      "format",
                      "has_effect",
                      "id",
                      "konami_id",
                      "level",
                      "link",
                      "linkmarker",
                      "misc",
                      "name",
                      "race",
                      "scale",
                      "sort",
                      "staple",
                      "startdate",
                      "tcgplayer_data",
                      "type",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "active" => true,
                  "index$" => 0,
                },
              ],
              "input" => "data",
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
      },
    }
  end


  def self.make_feature(name)
    require_relative 'features'
    YuGiOhFeatures.make_feature(name)
  end
end
